version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: scheduler-postgres
    environment:
      POSTGRES_USER: scheduler
      POSTGRES_PASSWORD: scheduler123
      POSTGRES_DB: scheduler_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
