name: Run tests and post coverage

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: read

jobs:
  run-tests-and-post-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Run dotnet test with coverage
      run: dotnet test --collect:"XPlat Code Coverage" --results-directory:tests/EnterpriseScheduler.Tests/CodeCoverage --settings tests/EnterpriseScheduler.Tests/coverage.runsettings
  
    - name: Code Coverage Report
      id: coverage_report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: tests/EnterpriseScheduler.Tests/CodeCoverage/*/coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '95 100'
      continue-on-error: true

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md

    - name: Fail if Coverage Thresholds Not Met
      if: steps.coverage_report.outcome == 'failure'
      run: exit 1
